services:
  mosquitto:
    image: eclipse-mosquitto
    network_mode: host
    volumes:
      - ../mosquitto/config:/mosquitto/config
      - ../mosquitto/data:/mosquitto/data
      - ../mosquitto/log:/mosquitto/log

  mppsolar:
    network_mode: host
    devices:
     - /dev/hidraw0:/dev/hidraw0
    volumes:
    #Bind over the configuration
      - type: bind
        source: ../mpp-solar/
        target: /etc/mpp-solar
    #Bind the code
      - type: bind
        source: ../..
        target: /mpp-solar
    build: .
    entrypoint:
      - powermon
      - -C
      - /etc/mpp-solar/powermon.yaml #Available due to volume binding above
      - --debug
#       - sleep
#       - infinity
    depends_on:
      - mosquitto

  mppsolar-api:
    network_mode: host
    build: 
      context: api
      dockerfile: Dockerfile.development
    entrypoint: 
      - node
      - index.js
    depends_on:
      - mppsolar


