# yaml config for powermon
device:
  name: Test_Inverter
  id: 123456789
  model: 8048MAX
  manufacturer: MPP-Solar
  port:
    type: test
    protocol: PI30MAX

commands:
- command: QPIGS  #0
  type: basic #so far not neccessary, might remove
  # trigger: # default to something sensible (only one of the below is needed/used)
  # - loops: 6 # run every 6 loops
  # trigger:
  # - at: "15:00" # run at/near to 3pm localtime
  trigger:
    every: 25 # run every 60 seconds (approx)
  # trigger: ondemand # (maybe) to allow config to be setup in advance??
  # trigger: disabled # excludes from 'once' runs
  outputs:
  - type: screen
    # format: hass
    # format: raw
    format: simple
  - type: screen
    # format: table
    format: 
      type: htmltable
      # #keep_case: True
      # #remove_spaces: False
      # #extra_info: True
      # filter: ^ac|^pv
- command: QPI  #1
  outputs:
  - type: screen
    format: table
- command: QID  #2
  outputs: screen
  trigger:
    at: "12:56"
- command: QMOD  #3
  trigger:
    loops: 50

daemon:
  # type: initd
  # keepalive: 100
