# yaml config for powermon
device:
  name: Test_Inverter
  id: 123456789
  model: 8048MAX
  manufacturer: MPP-Solar
  port:
    baud: 2400
    path: /dev/ttyUSB0
    type: test
    protocol: PI30MAX
commands:
- command: QED
  # f_command: f'QED{(date.today()-timedelta(days=1)).strftime("%Y%m%d")}'
  # f_command: f'QED{(date.today()).strftime("%Y%m%d")}'
  outputs:
  - type: screen
    format:
      type: simple
      tag: Test_Inverter
      filter: ^pv
loop: 60
mqttbroker:
  name: homeassistant.lan
  port: 1883
  username: null
  password: null
  adhoc_commands:
    topic: Test_Inverter/commands
    outputs:
    - name: screen
      tag: Test_Inverter