device:
  name: Test_Inverter
  id: 123456789
  model: 8048MAX
  manufacturer: MPP-Solar
  port:
    type: test
    protocol: PI30MAX
commands:
- command: QPGS0
  outputs:
  - type: screen
    format: 
      type: hass
      entity_id_prefix: inverter42
      discovery_prefix: homeassistant
      filter: ^serial|^work|^charger|^fault
