# yaml config for powermon
device:
  id: 123456789
  model: 1012LV-MK
  manufacturer: MPP-Solar
  port:
    path: /dev/hidraw0
    type: test
    protocol: PI30

commands:
- command: QPIGS #Must be in the protocol command list
  type: poll
  outputs:
  - type: screen
    format: table
          
mqttbroker:
  name: localhost
  port: 1883
  username: null
  password: null

api:
  announce_topic: powermon/announce
  adhoc_topic: powermon/adhoc
  
# daemon:
#   type: systemd
#   keepalive: 100