# yaml config for powermon
device:
  name: Test_Inverter
  serial_id: 123456789
  model: 8048MAX
  manufacturer: MPP-Solar
  port:
    type: test
    protocol: PI30MAX

#Separate the schedule from the device definition
scheduling:
  loop: 60
  schedules:
  - name: QPIGS_5_minutes
    type: loop
    run_every_x_loops: 5 #will run every 5 minutes
    commands:
    - command: QPIGS
      type: basic #default command type is basic
      outputs:
      - name: screen
        tag: Test_Inverter
    - command: QPIGS2
      type: basic
      outputs:
      - name: screen
        tag: Test_Inverter
  - name: 3pm_check
    type: time
    time: 15:00:00 #run at 3pm everyday
    commands:
    - command: QPGS0
      outputs:
      - name: screen
        tag: Test_Inverter
        filter: ^serial|^work|^charger|^fault
    - command: Q1
      outputs:
      - name: screen
        tag: Test_Inverter
        filter: ^inverter_charge
    - command: QED
      f_command: f'QED{(date.today()).strftime("%Y%m%d")}'
      outputs:
      - name: screen
        tag: Test_Inverter
        filter: ^pv

mqttbroker:
  name: localhost
  port: 1883
  user: null
  pass: null
  adhoc_commands:
    topic: Test_Inverter/commands
    outputs:
    - name: screen
      tag: Test_Inverter
daemon:
  type: systemd
  keepalive: 10
#daemon: initd

