{
 "title": "mpp_solar",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "About configuration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Solar Config",
   "type": "text",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# MPP_Solar\nThis Dashboard takes avantage of using prom output from mpp_solar with command output from QPGS and QPIGS.\nThis output can be directed to a text file while building the file, then moved to node_exporter folder as a prom file.\n\nDesigned for Rich Solar 6548 and should work for MPP LV6548 and the like. Should also work with other inverters though thresholds should be adjusted for each case based on the models abilities.\n\nAdjust your serial ports as needed. \n\n`Example configurations:`\n```\n# cat /etc/mppsolar/mpp_qpgs.conf\n[SETUP]\npause=5\n\n[Inverter_2]\nport=/dev/ttyUSB2\nprotocol=PI30max\ncommand=QPGS2\ntag=QPGS2\noutputs=prom\ndev=SCC2\n\n[Inverter_1]\nport=/dev/ttyUSB0\nprotocol=PI30max\ncommand=QPGS1\ntag=QPGS1\noutputs=prom\ndev=SCC1\n```\n\n\n```\n # cat /etc/mppsolar/mpp_qpigs.conf\n # This output required for Inverter heatsink temp, and PV1 charge wattage.\n[SETUP]\npause=5\n\n[Inverter_2]\nport=/dev/ttyUSB2\nprotocol=PI30max\ncommand=QPIGS\noutputs=prom\ndev=SCC2\n\n[Inverter_1]\nport=/dev/ttyUSB0\nprotocol=PI30max\ncommand=QPIGS\noutputs=prom\ndev=SCC1\n```\n```\n# cat /etc/mppsolar/mpp_qpigs2.conf\n### This config for inverters with more than one PV input, to retrive PV2 Charge Wattage output.\n### Thoogh not a requirement with this dashboard.\n[SETUP]\npause=5\n\n[Inverter_2]\nport=/dev/ttyUSB2\nprotocol=PI30max\ncommand=QPIGS2\noutputs=prom\ndev=SCC2\n\n[Inverter_1]\nport=/dev/ttyUSB0\nprotocol=PI30max\ncommand=QPIGS2\noutputs=prom\ndev=SCC1\n```\nExecutable in /usr/local/bin/\n```\n# cat /usr/local/bin/mpp-get-data.sh\n#!/bin/ash\ndataFile=\"mppsolar\"\ndataDir=\"/var/lib/node-exporter/mppsolar/\"\n\ncheckpath -d \"$dataDir\" -m 755 -o node_exporter:node_exporter\n\nwhile : ; do\n\n        `/usr/bin/mpp-solar -C /etc/mppsolar/mpp_qpgs.conf > ${dataDir}${dataFile}.$$` && \\\n        `/usr/bin/mpp-solar -C /etc/mppsolar/mpp_qpigs.conf >> ${dataDir}${dataFile}.$$` && \\\n        `/usr/bin/mpp-solar -C /etc/mppsolar/mpp_qpigs2.conf >> ${dataDir}${dataFile}.$$` && \\\n        mv ${dataDir}${dataFile}.$$ ${dataDir}${dataFile}.prom\n        sleep 5\ndone\n```\n\nCreate a SysV or systemd startup for the executable.\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
   }
  },
  { "title": "General Status ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Node System",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "Memory"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {mountpoint=\"/\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "Disk"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100",
     "legendFormat": "Swap"
    },
    { "expr": "(node_load1) * 40", "legendFormat": "System load" },
    { "expr": "node_hwmon_temp_celsius", "legendFormat": "{{chip}} Celsius" }
   ]
  },
  {
   "title": "Work Mode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mpp_solar_work_mode", "legendFormat": "Work Mode" }
   ]
  },
  {
   "title": "Source Mode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mpp_solar_charger_source_priority",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Fault Mode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mpp_solar_fault_code{cmd=~\"QPGS1|QPGS2\"}",
     "legendFormat": "Fault Code"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mpp_solar_is_load_on{cmd!=\"QPIGS\"}",
     "legendFormat": "{{inverter}} AC Load On"
    }
   ]
  },
  {
   "title": "SCC Battery Capacity",
   "type": "gauge",
   "description": "SOC",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mpp_solar_battery_capacity{cmd!=\"QPIGS\"}",
     "legendFormat": "{{inverter}}"
    },
    {
     "expr": "mpp_solar_battery_capacity{cmd!=\"QPIGS\"} offset 24h",
     "legendFormat": "{{inverter}} Yesterday"
    }
   ]
  },
  {
   "title": "AC Chargiing",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mpp_solar_is_ac_charging", "legendFormat": "{{inverter}}" }
   ]
  },
  {
   "title": "AC Lost",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mpp_solar_is_line_lost", "legendFormat": "{{inverter}} " }
   ]
  },
  {
   "title": "SCC Charging",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mpp_solar_is_scc_charging", "legendFormat": "{{inverter}} " }
   ]
  },
  {
   "title": "SCC OK",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mpp_solar_is_scc_ok", "legendFormat": "{{inverter}}" }
   ]
  },
  {
   "title": "Array Power by Inverter",
   "type": "gauge",
   "description": "Array power by Inverter",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(mpp_solar_pv1_input_current{cmd!~\"QPIGS\"} * mpp_solar_pv1_input_voltage{cmd!~\"QPIGS\"}) + (mpp_solar_pv2_input_voltage{cmd!~\"QPIGS2\"} * mpp_solar_pv2_input_current{cmd!~\"QPIGS2\"})",
     "legendFormat": "{{inverter}} Array Wattage"
    }
   ]
  },
  {
   "title": "AC Power Watts",
   "type": "gauge",
   "description": "AC load wattage on inverters",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mpp_solar_ac_output_active_power{cmd!=\"QPIGS\"}",
     "legendFormat": "{{inverter}} AC Watts"
    },
    {
     "expr": "sum(mpp_solar_ac_output_active_power{cmd!=\"QPIGS\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Array Wattage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mpp_solar_pv1_input_current{cmd!=\"QPIGS\"} * mpp_solar_pv1_input_voltage{cmd!=\"QPIGS\"}",
     "legendFormat": "{{inverter}} PV1"
    },
    {
     "expr": "mpp_solar_pv2_input_current{cmd!~\"QPIGS2\"} * mpp_solar_pv2_input_voltage{cmd!~\"QPIGS2\"}",
     "legendFormat": "{{inverter}}  PV2"
    }
   ]
  },
  {
   "title": "Inverter heat_sink temperature",
   "type": "gauge",
   "description": "Internal heatsink temperature of each inverter",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mpp_solar_inverter_heat_sink_temperature",
     "legendFormat": "{{inverter}}"
    }
   ]
  },
  {
   "title": "Grid Voltage",
   "type": "gauge",
   "description": "As detected by each inverter",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mpp_solar_ac_input_voltage", "legendFormat": "{{inverter}} Grid Volts" }
   ]
  },
  {
   "title": "AC Power Load ",
   "type": "gauge",
   "description": " AC Load %",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mpp_solar_load_percentage{}", "legendFormat": "{{inverter}}" }
   ]
  },
  {
   "title": "Battery Voltage ",
   "type": "gauge",
   "description": "Battery voltage",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mpp_solar_battery_voltage{cmd!=\"QPIGS\"}",
     "legendFormat": "{{inverter}}"
    }
   ]
  },
  { "title": "Inverters Drill Down", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Inverter AC Watts",
   "type": "graph",
   "description": "Inverters AC Wattage output",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "mpp_solar_ac_output_active_power{cmd!=\"QPIGS\"}",
     "legendFormat": "{{inverter}} AC Watts"
    },
    {
     "expr": "mpp_solar_ac_output_active_power{cmd!=\"QPIGS\"} offset 24h",
     "legendFormat": "{{inverter}} AC Watts Yesterday"
    }
   ]
  },
  {
   "title": "Inverter AC Load %",
   "type": "graph",
   "description": "Inverter AC Load Percent",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "mpp_solar_load_percentage{}", "legendFormat": "{{inverter}} AC Load %" },
    {
     "expr": "mpp_solar_load_percentage{} offset 24h",
     "legendFormat": "{{inverter}} AC Load % Yesterday"
    }
   ]
  },
  {
   "title": "Inverter heat_sink temperature",
   "type": "graph",
   "description": "Internal heatsink temperature of each inverter depends on QPIGS output.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "mpp_solar_inverter_heat_sink_temperature{}",
     "legendFormat": "{{inverter}}"
    },
    {
     "expr": "mpp_solar_inverter_heat_sink_temperature{} offset 24h",
     "legendFormat": "{{inverter}} Temp Yesterday"
    }
   ]
  },
  {
   "title": "Grid Voltage",
   "type": "graph",
   "description": "As detected by each inverter utilities voltage",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "mpp_solar_grid_voltage", "legendFormat": "{{inverter}} Grid Voltage" }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "graph",
   "description": "volts",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "mpp_solar_battery_voltage{cmd!=\"QPIGS\"}",
     "legendFormat": "{{inverter}} Battery Voltage"
    },
    {
     "expr": "mpp_solar_battery_voltage{cmd!=\"QPIGS\"} offset 24h",
     "legendFormat": "{{inverter}} Battery Voltage Yesterday"
    }
   ]
  },
  {
   "title": "Battery SOC",
   "type": "graph",
   "description": "SOC",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mpp_solar_battery_capacity{cmd!=\"QPIGS\"}",
     "legendFormat": "{{inverter}} SOC"
    },
    {
     "expr": "mpp_solar_battery_capacity{cmd!=\"QPIGS\"} offset 24h",
     "legendFormat": "{{inverter}} SOC Yesterday"
    }
   ]
  },
  {
   "title": "Battery current status",
   "type": "graph",
   "description": "Shows charging or discharging current",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "mpp_solar_battery_charging_current{cmd!~\"QPIGS\"} - mpp_solar_battery_discharge_current{cmd!~\"QPIGS\"}",
     "legendFormat": "{{inverter}} Charge"
    }
   ]
  },
  { "title": "Array Drill down", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Current by array",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "mpp_solar_pv1_input_current{cmd!=\"QPIGS\"}",
     "legendFormat": "{{inverter}} PV1"
    },
    {
     "expr": "mpp_solar_pv2_input_current{cmd!=\"QPIGS2\"}",
     "legendFormat": "{{inverter}} PV2"
    },
    {
     "expr": "mpp_solar_pv3_input_current{cmd!=\"QPIGS2\"}",
     "legendFormat": "{{inverter}} PV3"
    }
   ]
  },
  {
   "title": "Voltage by array",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "mpp_solar_pv1_input_voltage{cmd!=\"QPIGS\"}",
     "legendFormat": "{{inverter}} PV1"
    },
    {
     "expr": "mpp_solar_pv2_input_voltage{cmd!=\"QPIGS2\"}",
     "legendFormat": "{{inverter}} PV2"
    },
    {
     "expr": "mpp_solar_pv3_input_voltage{cmd!=\"QPIGS2\"}",
     "legendFormat": "{{inverter}} PV3"
    }
   ]
  },
  {
   "title": "Array Wattage",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "mpp_solar_pv1_input_current{cmd!~\"QPIGS\"} * mpp_solar_pv1_input_voltage{cmd!~\"QPIGS\"}",
     "legendFormat": "{{inverter}} PV1"
    },
    {
     "expr": "mpp_solar_pv2_input_current{cmd!~\"QPIGS2\"} * mpp_solar_pv2_input_voltage{cmd!~\"QPIGS2\"}",
     "legendFormat": "{{inverter}}  PV2"
    },
    {
     "expr": "mpp_solar_pv3_input_current{cmd!~\"QPIGS2\"} * mpp_solar_pv3_input_voltage{cmd!~\"QPIGS2\"}",
     "legendFormat": "{{inverter}}  PV3"
    },
    {
     "expr": "mpp_solar_pv1_input_current{cmd!~\"QPIGS\"} * mpp_solar_pv1_input_voltage{cmd!~\"QPIGS\"} offset 24h",
     "legendFormat": "{{inverter}} PV1 Yesterday"
    },
    {
     "expr": "mpp_solar_pv2_input_current{cmd!~\"QPIGS2\"} * mpp_solar_pv2_input_voltage{cmd!~\"QPIGS2\"} offset 24h",
     "legendFormat": "{{inverter}}  PV2 Yesterday"
    },
    {
     "expr": "mpp_solar_pv3_input_current{cmd!~\"QPIGS2\"} * mpp_solar_pv3_input_voltage{cmd!~\"QPIGS2\"} offset 24h",
     "legendFormat": "{{inverter}}  PV3 Yesterday"
    }
   ]
  },
  {
   "title": "PV Charging Watts",
   "type": "graph",
   "description": "Depends on QPIGS (PV1) and QPIGS2 (PV2-PV3) output. After MPPT.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "mpp_solar_pv1_charging_power", "legendFormat": "{{inverter}} PV1" },
    { "expr": "mpp_solar_pv2_charging_power", "legendFormat": "{{inverter}} PV2" }
   ]
  }
 ]
}