services:
  mppsolar:
    network_mode: host
    # devices:
    #  - /dev/hidraw0:/dev/hidraw0
    volumes:
    #Bind over the configuration
      # - type: bind
      #   source: ./docker/dev/config/
      #   target: /config
    #Bind the code
     - type: bind
       source: ../..
       target: /mpp-solar
    build:
      context: ./
      dockerfile: docker/dev-min/Dockerfile
    entrypoint:
      - powermon
      - -v
      # - /config/powermon-qpigs.yaml #Available due to volume binding above
      # - --debug
#       - sleep
#       - infinity



