services:
  mosquitto:
    image: eclipse-mosquitto
    network_mode: host
    volumes:
      - ../mosquitto/config:/mosquitto/config
      - ../mosquitto/data:/mosquitto/data
      - ../mosquitto/log:/mosquitto/log

  mppsolar:
    network_mode: host
    devices:
     - /dev/hidraw0:/dev/hidraw0
    volumes:
    #Bind over the configuration
      - type: bind
        source: ../mpp-solar/
        target: /etc/mpp-solar
    build: .
    entrypoint:
      - mpp-solar
      - -C
      - /etc/mpp-solar/mpp-solar.conf #Available due to volume binding above
      - --daemon
    depends_on:
      - mosquitto


