""" powermon / protocols / pi30max.py """
import logging

from powermon.commands.result import ResultType
from powermon.protocols.pi30 import PI30
from powermon.commands.reading_definition import ResponseType
from powermon.commands.reading_definition import ReadingType
from powermon.commands.parameter import ParameterType
from powermon.commands.parameter import ParameterFormat

log = logging.getLogger("pi30max")

NEW_QUERY_COMMANDS = {
    "QSID": {
        "name": "QSID",
        "description": "Device Serial Number inquiry",
        "help": " -- queries the device serial number (length greater than 14)",
        "result_type": ResultType.SINGLE,
        "reading_definitions": [{"description": "Serial Number",
                                    "reading_type": ReadingType.MESSAGE, "icon": "mdi:identifier",
                                    "response_type": ResponseType.TEMPLATE_BYTES, "format_template" : "r[2:int(r[0:2])+2]"}],
        "test_responses": [b"(1492932105105335005535\x94\x0e\r", ],
    },
    "QVFW3": {
        "name": "QVFW3",
        "description": "Remote CPU firmware version inquiry",
        "result_type": ResultType.SINGLE,
        "reading_definitions": [{"description": "Remote CPU firmware version", "reading_type": ReadingType.MESSAGE, "response_type": ResponseType.TEMPLATE_BYTES, "format_template" : "r.removeprefix('VERFW:')", "icon": "mdi:identifier"}],
        "test_responses": [b"(VERFW:00072.70\x53\xA7\r", ],
    },
    "VERFW": {
        "name": "VERFW",
        "description": "Bluetooth version inquiry",
        "result_type": ResultType.SINGLE,
        "reading_definitions": [{"description": "Bluetooth firmware version", "reading_type": ReadingType.MESSAGE, "response_type": ResponseType.TEMPLATE_BYTES, "format_template" : "r.removeprefix('VERFW:')", "icon": "mdi:identifier"}],
        "test_responses": [b"(VERFW:00072.70\x53\xA7\r", ],
    },
    "QFLAG": {
        "name": "QFLAG",
        "description": "Flag Status inquiry",
        "help": " -- queries the enabled / disabled state of various Inverter settings (e.g. buzzer, overload, interrupt alarm)",
        "result_type": ResultType.SINGLE,
        "reading_definitions": [
            {
                "description": "Device Status",
                "reading_type": ReadingType.MULTI_ENABLE_DISABLE,
                "response_type": ResponseType.ENABLE_DISABLE_FLAGS,
                "options": {
                    "a": "Buzzer",
                    "b": "Overload Bypass",
                    "d": "Solar Feed to Grid",
                    "k": "LCD Reset to Default",
                    "u": "Overload Restart",
                    "v": "Over Temperature Restart",
                    "x": "LCD Backlight",
                    "y": "Primary Source Interrupt Alarm",
                    "z": "Record Fault Code",
                },
            }
        ],
        "test_responses": [
            b"(EakxyDbduvz\x8d\x73\r",
        ],
    },
    "QPIRI": {
        "name": "QPIRI",
        "description": "Current Settings inquiry",
        "result_type": ResultType.ORDERED,
        "reading_definitions": [
            {"description": "AC Input Voltage", "reading_type": ReadingType.VOLTS, "response_type": ResponseType.FLOAT, "icon": "mdi:transmission-tower-import", "device-class": "voltage"},
            {"description": "AC Input Current", "reading_type": ReadingType.CURRENT, "response_type":ResponseType.FLOAT, "icon": "mdi:current-ac", "device-class": "current"},
            {"description": "AC Output Voltage", "reading_type": ReadingType.VOLTS, "response_type": ResponseType.FLOAT, "icon": "mdi:transmission-tower-export", "device-class": "voltage"},
            {"description": "AC Output Frequency", "reading_type": ReadingType.FREQUENCY, "response_type": ResponseType.FLOAT, "icon": "mdi:current-ac", "device-class": "frequency"},
            {"description": "AC Output Current", "reading_type": ReadingType.CURRENT, "response_type": ResponseType.FLOAT, "icon": "mdi:current-ac", "device-class": "current"},
            {"description": "AC Output Apparent Power", "reading_type": ReadingType.APPARENT_POWER, "response_type": ResponseType.INT, "icon": "mdi:power-plug", "device-class": "apparent_power"},
            {"description": "AC Output Active Power", "reading_type": ReadingType.WATTS, "response_type": ResponseType.INT, "icon": "mdi:power-plug", "device-class": "power", "state_class": "measurement"},
            {"description": "Battery Voltage", "reading_type": ReadingType.VOLTS, "response_type": ResponseType.FLOAT, "icon": "mdi:battery-outline", "device-class": "voltage"},
            {"description": "Battery Recharge Voltage", "reading_type": ReadingType.VOLTS, "response_type": ResponseType.FLOAT, "icon": "mdi:battery-outline", "device-class": "voltage"},
            {"description": "Battery Under Voltage", "reading_type": ReadingType.VOLTS, "response_type": ResponseType.FLOAT, "icon": "mdi:battery-outline", "device-class": "voltage"},
            {"description": "Battery Bulk Charge Voltage", "reading_type": ReadingType.VOLTS, "response_type": ResponseType.FLOAT, "icon": "mdi:battery-outline", "device-class": "voltage"},
            {"description": "Battery Float Charge Voltage", "reading_type": ReadingType.VOLTS, "response_type": ResponseType.FLOAT, "icon": "mdi:battery-outline", "device-class": "voltage"},
            {
                "description": "Battery Type",
                "reading_type": ReadingType.MESSAGE,
                "response_type": ResponseType.LIST,
                "options": [
                    "AGM",
                    "Flooded",
                    "User",
                    "Pylontech",
                    "Shinheung",
                    "WECO",
                    "Soltaro",
                    "TBD",
                    "LIb-protocol compatible",
                    "3rd party Lithium",
                ],
            },
            {"description": "Max AC Charging Current", "reading_type": ReadingType.CURRENT, "response_type": ResponseType.INT, "icon": "mdi:current-ac", "device-class": "current"},
            {"description": "Max Charging Current", "reading_type": ReadingType.CURRENT, "response_type": ResponseType.INT, "icon": "mdi:current-ac", "device-class": "current"},
            {"description": "Input Voltage Range", "reading_type": ReadingType.MESSAGE, "response_type": ResponseType.LIST, "options": ["Appliance", "UPS"]},
            {
                "description": "Output Source Priority",
                "reading_type": ReadingType.MESSAGE,
                "response_type": ResponseType.LIST,
                "options": [
                    "Utility Solar Battery",
                    "Solar Utility Battery",
                    "Solar Battery Utility",
                ],
            },
            {
                "description": "Charger Source Priority",
                "reading_type": ReadingType.MESSAGE,
                "response_type": ResponseType.LIST,
                "options": [
                    "Utility first",
                    "Solar first",
                    "Solar + Utility",
                    "Only solar charging permitted",
                ],
            },
            {"description": "Max Parallel Units", "reading_type": ReadingType.MESSAGE, "response_type": ResponseType.INT},
            {"description": "Machine Type", "reading_type": ReadingType.MESSAGE, "response_type": ResponseType.OPTION, "options": {"00": "Grid tie", "01": "Off Grid", "10": "Hybrid"}},
            {"description": "Topology", "reading_type": ReadingType.MESSAGE, "response_type": ResponseType.LIST, "options": ["transformerless", "transformer"]},
            {
                "description": "Output Mode",
                "reading_type": ReadingType.MESSAGE,
                "response_type": ResponseType.LIST,
                "options": [
                    "single machine output",
                    "parallel output",
                    "Phase 1 of 3 Phase output",
                    "Phase 2 of 3 Phase output",
                    "Phase 3 of 3 Phase output",
                    "Phase 1 of 2 phase output",
                    "Phase 2 of 2 phase output (120°)",
                    "Phase 2 of 2 phase output (180°)",
                    "unknown output",
                ],
            },
            {"description": "Battery Redischarge Voltage", "reading_type": ReadingType.VOLTS, "response_type": ResponseType.FLOAT},
            {
                "description": "PV OK Condition",
                "reading_type": ReadingType.MESSAGE, "response_type": ResponseType.LIST,
                "options": [
                    "As long as one unit of inverters has connect PV, parallel system will consider PV OK",
                    "Only All of inverters have connect PV, parallel system will consider PV OK",
                ],
            },
            {
                "description": "PV Power Balance",
                "reading_type": ReadingType.MESSAGE, "response_type": ResponseType.LIST,
                "options": [
                    "PV input max current will be the max charged current",
                    "PV input max power will be the sum of the max charged power and loads power",
                ],
            },
            {"description": "Max charging time for CV stage", "reading_type": ReadingType.TIME_MINUTES, "response_type": ResponseType.INT},
            {"description": "Operation Logic", "reading_type": ReadingType.MESSAGE, "response_type": ResponseType.LIST, "options": ["Automatic mode", "On-line mode", "ECO mode"]},
            {"description": "Max discharging current", "reading_type": ReadingType.CURRENT, "response_type": ResponseType.INT, "icon": "mdi:current-ac", "device-class": "current"},
        ],
        "test_responses": [
            b"(230.0 21.7 230.0 50.0 21.7 5000 4000 48.0 46.0 42.0 56.4 54.0 0 10 010 1 0 0 6 01 0 0 54.0 0 1\x6F\x7E\r",
        ],
    },
    "QPIGS": {
        "name": "QPIGS",
        "description": "General Status Parameters inquiry",
        "result_type": ResultType.ORDERED,
        "reading_definitions": [
            {"description": "AC Input Voltage",
                "reading_type": ReadingType.VOLTS, "icon": "mdi:transmission-tower-export", "device-class": "voltage",
                "response_type": ResponseType.FLOAT},
            {"description": "AC Input Frequency", "reading_type": ReadingType.FREQUENCY,
                "response_type": ResponseType.FLOAT,
                "icon": "mdi:current-ac", "device-class": "frequency"},
            {"description": "AC Output Voltage", "reading_type": ReadingType.VOLTS, "response_type": ResponseType.FLOAT, "icon": "mdi:power-plug", "device-class": "voltage"},
            {"description": "AC Output Frequency",
                "reading_type": ReadingType.FREQUENCY, "icon": "mdi:current-ac", "device-class": "frequency",
                "response_type": ResponseType.FLOAT},
            {"description": "AC Output Apparent Power",
                "reading_type": ReadingType.APPARENT_POWER, "icon": "mdi:power-plug", "device-class": "apparent_power",
                "response_type": ResponseType.INT},
            {"description": "AC Output Active Power",
                "reading_type": ReadingType.WATTS, "icon": "mdi:power-plug", "device-class": "power", "state_class": "measurement",
                "response_type": ResponseType.INT},
            {"description": "AC Output Load", "reading_type": ReadingType.PERCENTAGE, "response_type": ResponseType.INT, "icon": "mdi:brightness-percent"},
            {"description": "BUS Voltage", "reading_type": ReadingType.VOLTS, "response_type": ResponseType.INT, "icon": "mdi:details", "device-class": "voltage"},
            {"description": "Battery Voltage", "reading_type": ReadingType.VOLTS, "response_type": ResponseType.FLOAT, "icon": "mdi:battery-outline", "device-class": "voltage"},
            {"description": "Battery Charging Current",
                "reading_type": ReadingType.CURRENT, "icon": "mdi:current-dc", "device-class": "current",
                "response_type": ResponseType.INT},
            {"description": "Battery Capacity", "reading_type": ReadingType.PERCENTAGE, "response_type": ResponseType.INT, "device-class": "battery"},
            {"description": "Inverter Heat Sink Temperature",
                "reading_type": ReadingType.TEMPERATURE, "icon": "mdi:details", "device-class": "temperature",
                "response_type": ResponseType.INT},
            {"description": "PV1 Input Current", "reading_type": ReadingType.CURRENT, "response_type": ResponseType.FLOAT, "icon": "mdi:solar-power", "device-class": "current"},
            {"description": "PV1 Input Voltage", "reading_type": ReadingType.VOLTS, "response_type": ResponseType.FLOAT, "icon": "mdi:solar-power", "device-class": "voltage"},
            {"description": "Battery Voltage from SCC",
                "reading_type": ReadingType.VOLTS, "icon": "mdi:battery-outline", "device-class": "voltage",
                "response_type": ResponseType.FLOAT},
            {"description": "Battery Discharge Current",
                "reading_type": ReadingType.CURRENT, "icon": "mdi:battery-negative", "device-class": "current",
                "response_type": ResponseType.INT},
            {"description": "Device Status",
                "reading_type": ReadingType.FLAGS,
                "response_type": ResponseType.FLAGS,
                "flags": [
                    "Is SBU Priority Version Added",
                    "Is Configuration Changed",
                    "Is SCC Firmware Updated",
                    "Is Load On",
                    "Is Battery Voltage to Steady While Charging",
                    "Is Charging On",
                    "Is SCC Charging On",
                    "Is AC Charging On",
                ]},
            {"description": "Battery Voltage Offset for Fans On (10mV)", "reading_type": ReadingType.VOLTS, "response_type": ResponseType.INT},
            {"description": "EEPROM Version",  "reading_type": ReadingType.MESSAGE, "response_type": ResponseType.INT},
            {"description": "PV1 Charging Power",
                "reading_type": ReadingType.WATTS, "icon": "mdi:solar-power", "device-class": "power", "state_class": "measurement",
                "response_type": ResponseType.INT},
            {"description": "Device Status2",
                "reading_type": ReadingType.FLAGS, 
                "response_type": ResponseType.FLAGS, "flags": ["Is Charging to Float", "Is Switched On", "Is Dustproof Installed"]},
            {"description": "Solar Feed to Grid",  "reading_type": ReadingType.MESSAGE, "response_type": ResponseType.LIST, "options": ["Disabled", "Enabled"]},
            {"description": "Country",
                "reading_type": ReadingType.MESSAGE, 
                "response_type": ResponseType.OPTION, 
                "options": {
                    "00": "India",
                    "01": "Germany",
                    "02": "South America",
                },
            },
            {"description": "Solar Feed to Grid Power",
                "reading_type": ReadingType.WATTS, "icon": "mdi:solar-power", "device-class": "power", "state_class": "measurement",
                "response_type": ResponseType.INT},
        ],
        "test_responses": [
            b"(227.2 50.0 230.3 50.0 0829 0751 010 447 54.50 020 083 0054 02.7 323.6 00.00 00000 00010110 00 00 00879 010\xf1\x8c\r",
            b"(227.2 50.0 230.3 50.0 0829 0751 010 447 54.50 020 083 0054 02.7 323.6 00.00 00000 00010110 00 00 00879 010 1 02 123\x1c\x84\r",
        ],
    },
}
QUERY_COMMANDS = {
    "QPIGS2": {
        "name": "QPIGS2",
        "description": "General Status Parameters inquiry 2",
        "response_type": ResultType.INDEXED,
        "response": [
            [0, "PV2 Input Current", ResponseType.FLOAT, "A", {"icon": "mdi:solar-power", "device-class": "current"}],
            [1, "PV2 Input Voltage", ResponseType.FLOAT, "V", {"icon": "mdi:solar-power", "device-class": "voltage"}],
            [
                2,
                "PV2 Charging Power",
                ResponseType.INT,
                "W",
                {"icon": "mdi:solar-power", "device-class": "power", "state_class": "measurement"},
            ],
        ],
        "test_responses": [
            b"(03.1 327.3 01026 \xc9\x8b\r",
        ],
    },
    "QPGS": {
        "name": "QPGS",
        "description": "Parallel Information inquiry",
        "help": " -- example: QPGS0 queries the values of various metrics from instance 0 of parallel setup Inverters",
        "response_type": ResultType.INDEXED,
        "response": [
            [0, "Parallel instance number", ResponseType.OPTION, ["Not valid", "valid"]],
            #[1, "Serial number", "bytes:r.decode()", "", {"icon": "mdi:identifier"}],
            [1, "Serial number", ResponseType.BYTES, "", {"icon": "mdi:identifier"}],
            [
                2,
                "Work mode",
                ResponseType.OPTION,
                {
                    "P": "Power On Mode",
                    "S": "Standby Mode",
                    "L": "Line Mode",
                    "B": "Battery Mode",
                    "F": "Fault Mode",
                    "H": "Power Saving Mode",
                    "D": "Shutdown Mode",
                    "Y": "Bypass",
                },
            ],
            [
                3,
                "Fault code",
                ResponseType.OPTION,
                {
                    "00": "No fault",
                    "01": "Fan is locked",
                    "02": "Over temperature",
                    "03": "Battery voltage is too high",
                    "04": "Battery voltage is too low",
                    "05": "Output short circuited or Over temperature",
                    "06": "Output voltage is too high",
                    "07": "Over load time out",
                    "08": "Bus voltage is too high",
                    "09": "Bus soft start failed",
                    "10": "PV over current",
                    "11": "PV over voltage",
                    "12": "DC over current",
                    "13": "Battery discharge over current",
                    "51": "Over current inverter",
                    "52": "Bus voltage too low",
                    "53": "Inverter soft start failed",
                    "54": "Self-test failed",
                    "55": "Over DC voltage on output of inverter",
                    "56": "Battery connection is open",
                    "57": "Current sensor failed",
                    "58": "Output voltage is too low",
                    "60": "Power feedback protection",
                    "71": "Firmware version different",
                    "72": "Current sharing fault",
                    "80": "CAN communication failed",
                    "81": "Parallel host line lost",
                    "82": "Parallel synchronized signal lost",
                    "83": "Parallel battery voltage detect different",
                    "84": "AC input voltage or frequency detected different",
                    "85": "AC output current unbalanced",
                    "86": "AC output mode setting different",
                },
            ],
            [4, "Grid Voltage", ResponseType.FLOAT, "V", {"icon": "mdi:power-plug", "device-class": "voltage"}],
            [5, "Grid Frequency", ResponseType.FLOAT, "Hz", {"icon": "mdi:current-ac", "device-class": "frequency"}],
            [6, "AC Output Voltage", ResponseType.FLOAT, "V", {"icon": "mdi:power-plug", "device-class": "voltage"}],
            [7, "AC Output Frequency", ResponseType.FLOAT, "Hz", {"icon": "mdi:current-ac", "device-class": "frequency"}],
            [8, "AC Output Apparent Power", ResponseType.INT, "VA", {"icon": "mdi:power-plug", "device-class": "apparent_power"}],
            [
                9,
                "AC Output Active Power",
                ResponseType.INT,
                "W",
                {"icon": "mdi:power-plug", "device-class": "power", "state_class": "measurement"},
            ],
            [10, "Load Percentage", ResponseType.INT, "%", {"icon": "mdi:brightness-percent"}],
            [11, "Battery Voltage", ResponseType.FLOAT, "V", {"icon": "mdi:battery-outline", "device-class": "voltage"}],
            [12, "Battery Charging Current", ResponseType.INT, "A", {"icon": "mdi:current-dc", "device-class": "current"}],
            [13, "Battery Capacity", ResponseType.INT, "%", {"device-class": "battery"}],
            [14, "PV1 Input Voltage", ResponseType.FLOAT, "V", {"icon": "mdi:solar-power", "device-class": "voltage"}],
            [
                15,
                "Total Charging Current",
                ResponseType.INT,
                "A",
                {"icon": "mdi:brightness-percent", "device-class": "current"},
            ],
            [
                16,
                "Total AC Output Apparent Power",
                ResponseType.INT,
                "VA",
                {"icon": "mdi:power-plug", "device-class": "apparent_power"},
            ],
            [
                17,
                "Total Output Active Power",
                ResponseType.INT,
                "W",
                {"icon": "mdi:power-plug", "device-class": "power", "state_class": "measurement"},
            ],
            [
                18,
                "Total AC Output Percentage",
                ResponseType.INT,
                "%",
                {"icon": "mdi:brightness-percent"},
            ],
            [
                19,
                "Inverter Status",
                ResponseType.FLAGS,
                [
                    "Is SCC OK",
                    "Is AC Charging",
                    "Is SCC Charging",
                    "Is Battery Over Voltage",
                    "Is Battery Under Voltage",
                    "Is Line Lost",
                    "Is Load On",
                    "Is Configuration Changed",
                ],
            ],
            [
                20,
                "Output mode",
                ResponseType.OPTION,
                [
                    "single machine",
                    "parallel output",
                    "Phase 1 of 3 phase output",
                    "Phase 2 of 3 phase output",
                    "Phase 3 of 3 phase output",
                    "Phase 1 of 2 phase output",
                    "Phase 2 of 2 phase output (120°)",
                    "Phase 2 of 2 phase output (180°)",
                    "Unknown Output Mode",
                ],
            ],
            [
                21,
                "Charger source priority",
                ResponseType.OPTION,
                ["Utility first", "Solar first", "Solar + Utility", "Solar only"],
            ],
            [22, "Max Charger Current", ResponseType.INT, "A", {"device-class": "current"}],
            [23, "Max Charger Range", ResponseType.INT, "A", {"device-class": "current"}],
            [24, "Max AC Charger Current", ResponseType.INT, "A", {"device-class": "current"}],
            [25, "PV1 Input Current", ResponseType.INT, "A", {"icon": "mdi:solar-power", "device-class": "power"}],
            [
                26,
                "Battery Discharge Current",
                ResponseType.INT,
                "A",
                {"icon": "mdi:battery-negative", "device-class": "current"},
            ],
            [27, "PV2 Input Voltage", ResponseType.FLOAT, "V", {"icon": "mdi:solar-power", "device-class": "voltage"}],
            [28, "PV2 Input Current", ResponseType.INT, "A", {"icon": "mdi:solar-power", "device-class": "current"}],
        ],
        "test_responses": [
            b"(0 92932105105315 B 00 000.0 00.00 230.0 50.00 0989 0907 012 53.2 009 090 349.8 009 00989 00907 011 10100110 0 1 100 120 030 02 000 275.3 02i]\r",
        ],
        "regex": "QPGS(\\d+)$",
    },
    "QMOD": {
        "name": "QMOD",
        "description": "Mode inquiry",
        "response_type": ResultType.INDEXED,
        "response": [
            [
                0,
                "Device Mode",
                ResponseType.OPTION,
                {
                    "P": "Power on",
                    "S": "Standby",
                    "L": "Line",
                    "B": "Battery",
                    "F": "Fault",
                    "H": "Power Saving",
                    "D": "Shutdown",
                },
            ]
        ],
        "test_responses": [
            b"(S\xe5\xd9\r",
            b"(B\xe7\xc9\r",
        ],
    },
    "QPIWS": {
        "name": "QPIWS",
        "description": "Warning status inquiry",
        "response_type": ResultType.INDEXED,
        "response": [
            [
                0,
                "Warning",
                ResponseType.FLAGS,
                [
                    "PV loss warning",
                    "Inverter fault",
                    "Bus over fault",
                    "Bus under fault",
                    "Bus soft fail fault",
                    "Line fail warning",
                    "OPV short warning",
                    "Inverter voltage too low fault",
                    "Inverter voltage too high fault",
                    "Over temperature fault",
                    "Fan locked fault",
                    "Battery voltage to high fault",
                    "Battery low alarm warning",
                    "Reserved",
                    "Battery under shutdown warning",
                    "Battery derating warning",
                    "Overload fault",
                    "EEPROM fault",
                    "Inverter over current fault",
                    "Inverter soft fail fault",
                    "Self test fail fault",
                    "OP DC voltage over fault",
                    "Bat open fault",
                    "Current sensor fail fault",
                    "Battery short fault",
                    "Power limit warning",
                    "PV voltage high warning",
                    "MPPT overload fault",
                    "MPPT overload warning",
                    "Battery too low to charge warning",
                    "",
                    "Battery weak",
                    "Battery weak",
                    "Battery weak",
                    "",
                    "Battery equalisation warning",
                ],
            ]
        ],
        "test_responses": [
            b"(00000100000000001000000000000000\x56\xA6\r",
            b"(000000000000000000000000000000000000<\x8e\r",
        ],
    },
    "QDI": {
        "name": "QDI",
        "description": "Default Settings inquiry",
        "response_type": ResultType.INDEXED,
        "response": [
            [0, "AC Output Voltage", ResponseType.FLOAT, "V"],
            [1, "AC Output Frequency", ResponseType.FLOAT, "Hz"],
            [2, "Max AC Charging Current", ResponseType.INT, "A"],
            [3, "Battery Under Voltage", ResponseType.FLOAT, "V"],
            [4, "Battery Float Charge Voltage", ResponseType.FLOAT, "V"],
            [5, "Battery Bulk Charge Voltage", ResponseType.FLOAT, "V"],
            [6, "Battery Recharge Voltage", ResponseType.FLOAT, "V"],
            [7, "Max Charging Current", ResponseType.INT, "A"],
            [8, "Input Voltage Range", ResponseType.OPTION, ["Appliance", "UPS"]],
            [
                9,
                "Output Source Priority",
                ResponseType.OPTION,
                ["Utility first", "Solar first", "SBU first"],
            ],
            [
                10,
                "Charger Source Priority",
                ResponseType.OPTION,
                [
                    "Utility first",
                    "Solar first",
                    "Solar + Utility",
                    "Only solar charging permitted",
                ],
            ],
            [
                11,
                "Battery Type",
                ResponseType.OPTION,
                [
                    "AGM",
                    "Flooded",
                    "User",
                    "TBD",
                    "Pylontech",
                    "WECO",
                    "Soltaro",
                    "LIb-protocol compatible",
                    "3rd party Lithium",
                ],
            ],
            [12, "Buzzer", ResponseType.OPTION, ["enabled", "disabled"]],
            [13, "Power saving", ResponseType.OPTION, ["disabled", "enabled"]],
            [14, "Overload restart", ResponseType.OPTION, ["disabled", "enabled"]],
            [15, "Over temperature restart", ResponseType.OPTION, ["disabled", "enabled"]],
            [16, "LCD Backlight", ResponseType.OPTION, ["disabled", "enabled"]],
            [17, "Primary source interrupt alarm", ResponseType.OPTION, ["disabled", "enabled"]],
            [18, "Record fault code", ResponseType.OPTION, ["disabled", "enabled"]],
            [19, "Overload bypass", ResponseType.OPTION, ["disabled", "enabled"]],
            [20, "LCD reset to default", ResponseType.OPTION, ["disabled", "enabled"]],
            [
                21,
                "Output mode",
                ResponseType.OPTION,
                [
                    "single machine",
                    "parallel output",
                    "Phase 1 of 3 phase output",
                    "Phase 2 of 3 phase output",
                    "Phase 3 of 3 phase output",
                    "Phase 1 of 2 phase output",
                    "Phase 2 of 2 phase output (120°)",
                    "Phase 2 of 2 phase output (180°)",
                    "Unknown Output Mode",
                ],
            ],
            [22, "Battery Redischarge Voltage", ResponseType.FLOAT, "V"],
            [
                23,
                "PV OK condition",
                ResponseType.OPTION,
                [
                    "As long as one unit of inverters has connect PV, parallel system will consider PV OK",
                    "Only All of inverters have connect PV, parallel system will consider PV OK",
                ],
            ],
            [
                24,
                "PV Power Balance",
                ResponseType.OPTION,
                [
                    "PV input max current will be the max charged current",
                    "PV input max power will be the sum of the max charged power and loads power",
                ],
            ],
            [25, "Max Charging Time at CV", ResponseType.INT, "min"],
            [26, "Max Discharging current", ResponseType.INT, "A"],
        ],
        "test_responses": [
            b"(230.0 50.0 0030 44.0 54.0 56.4 46.0 60 0 0 2 0 0 0 0 0 1 1 1 0 1 0 54.0 0 1 224\xeb\xbc\r",
        ],
    },
    "QOPPT": {
        "name": "QOPPT",
        "description": "Device Output Source Priority Time Order Inquiry",
        "response_type": ResultType.INDEXED,
        "response": [[0, "Output Source Priority 00 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     [1, "Output Source Priority 01 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     [2, "Output Source Priority 02 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     [3, "Output Source Priority 03 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     [4, "Output Source Priority 04 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     [5, "Output Source Priority 05 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     [6, "Output Source Priority 06 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     [7, "Output Source Priority 07 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     [8, "Output Source Priority 08 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     [9, "Output Source Priority 09 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     [10, "Output Source Priority 10 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     [11, "Output Source Priority 11 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     [12, "Output Source Priority 12 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     [13, "Output Source Priority 13 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     [14, "Output Source Priority 14 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     [15, "Output Source Priority 15 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     [16, "Output Source Priority 16 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     [17, "Output Source Priority 17 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     [18, "Output Source Priority 18 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     [19, "Output Source Priority 19 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     [20, "Output Source Priority 20 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     [21, "Output Source Priority 21 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     [22, "Output Source Priority 22 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     [23, "Output Source Priority 23 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     [24, "Device Output Source Priority", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     [25, "Selection of Output Source Priority Order 1", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     [26, "Selection of Output Source Priority Order 2", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     [27, "Selection of Output Source Priority Order 3", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"]],
                     ],
        "test_responses": [
            b"(2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 1>>\r",
        ],
    },
    "QCHPT": {
        "name": "QCHPT",
        "description": "Device Charger Source Priority Time Order Inquiry",
        "response_type": ResultType.INDEXED,
        "response": [
            [0, "Charger Source Priority 00 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
            [1, "Charger Source Priority 01 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
            [2, "Charger Source Priority 02 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
            [3, "Charger Source Priority 03 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
            [4, "Charger Source Priority 04 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
            [5, "Charger Source Priority 05 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
            [6, "Charger Source Priority 06 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
            [7, "Charger Source Priority 07 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
            [8, "Charger Source Priority 08 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
            [9, "Charger Source Priority 09 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
            [10, "Charger Source Priority 10 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
            [11, "Charger Source Priority 11 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
            [12, "Charger Source Priority 12 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
            [13, "Charger Source Priority 13 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
            [14, "Charger Source Priority 14 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
            [15, "Charger Source Priority 15 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
            [16, "Charger Source Priority 16 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
            [17, "Charger Source Priority 17 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
            [18, "Charger Source Priority 18 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
            [19, "Charger Source Priority 19 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
            [20, "Charger Source Priority 20 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
            [21, "Charger Source Priority 21 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
            [22, "Charger Source Priority 22 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
            [23, "Charger Source Priority 23 hours", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
            [24, "Device Charger Source Priority", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
            [25, "Selection of Charger Source Priority Order 1", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
            [26, "Selection of Charger Source Priority Order 2", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
            [27, "Selection of Charger Source Priority Order 3", ResponseType.OPTION, ["undefined", "Solar first", "Solar + Utility", "Only Solar"],],
        ],
        "test_responses": [
            b"(3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 0 0 0\xd0\x8b\r",
        ],
    },
    "QT": {
        "name": "QT",
        "description": "Device Time Inquiry",
        "response_type": ResultType.INDEXED,
        "response": [[0, "Device Time", ResponseType.BYTES, ""]],
        "test_responses": [
            b"(20210726122606JF\r",
        ],
    },
    "QBEQI": {
        "name": "QBEQI",
        "description": "Battery Equalization Status Parameters Inquiry",
        "response_type": ResultType.INDEXED,
        "response": [
            [0, "Equalization Enabled", ResponseType.OPTION, ["Disabled", "Enabled"]],
            [1, "Equalization Time", ResponseType.INT, "min"],
            [2, "Equalization Period", ResponseType.INT, "day"],
            [3, "Equalization Max Current", ResponseType.INT, "A"],
            [4, "Reserved1", ResponseType.BYTES, ""],
            [5, "Equalization Voltage", ResponseType.FLOAT, "V"],
            [6, "Reserved2", ResponseType.BYTES, ""],
            [7, "Equalization Over Time", ResponseType.INT, "min"],
            [8, "Equalization Active", ResponseType.OPTION, ["Inactive", "Active"]],
            [9, "Equalization Elasped Time", ResponseType.INT, "hour"],
        ],
        "test_responses": [
            b"(1 030 030 080 021 55.40 224 030 0 0234y?\r",
        ],
    },
    "QET": {
        "name": "QET",
        "description": "Total PV Generated Energy Inquiry",
        "response_type": ResultType.INDEXED,
        "response": [
            [0,
                "Total PV Generated Energy", ResponseType.INT,
                "Wh",
                {"icon": "mdi:solar-power", "device-class": "energy", "state_class": "total"},
             ]
        ],
        "test_responses": [
            b"(00238800!J\r",
        ],
    },
    "QEY": {
        "name": "QEY",
        "description": "Yearly PV Generated Energy Inquiry",
        "response_type": ResultType.INDEXED,
        "response": [
            [0,
                "PV Generated Energy for Year", ResponseType.INT, "Wh",
                {"icon": "mdi:counter", "device-class": "energy", "state_class": "total"},
             ],
            [1, "Year", ResponseType.INFO+":cn[3:]", ""],
        ],
        "test_responses": [
            b"(00238800!J\r",
        ],
        "regex": "QEY(\\d\\d\\d\\d)$",
    },
    "QEM": {
        "name": "QEM",
        "description": "Monthly PV Generated Energy Inquiry",
        "response_type": ResultType.INDEXED,
        "response": [
            [0, "PV Generated Energy for Month", ResponseType.INT, "Wh", {"icon": "mdi:solar-power", "device-class": "energy", "state_class": "total"},],
            [1, "Year", ResponseType.INFO+":cn[3:7]", ""],
            [2, "Month", ResponseType.INFO+":calendar.month_name[int(cn[7:])]", ""],
        ],
        "test_responses": [
            b"(00238800!J\r",
        ],
        "regex": "QEM(\\d\\d\\d\\d\\d\\d)$",
    },
    "QED": {
        "name": "QED",
        "description": "Daily PV Generated Energy Inquiry",
        "help": " -- display daily generated energy, format is QEDyyyymmdd",
        "result_type": ResultType.INDEXED,
        "reading_definitions": [
            {"index":0, "description":"PV Generated Energy for Day", "reading_type":ReadingType.WATT_HOURS, "response_type":ResponseType.INT, "icon": "mdi:solar-power", "device-class": "energy", "state_class": "total"},
        ],
        "parameters": [
            {"name":"date", "description":"Date for query", "parameter_type":ParameterType.DATE, "parameter_format":ParameterFormat.YYYYMMDD}
        ],
        "test_responses": [
            b"(00238800!J\r",
        ],
        "regex": "QED(\\d\\d\\d\\d\\d\\d\\d\\d)$", 
    },
    "QLT": {
        "name": "QLT",
        "description": "Total Output Load Energy Inquiry",
        "response_type": ResultType.INDEXED,
        "response": [
            [0, "Total Output Load Energy", ResponseType.INT, "Wh", {"icon": "mdi:counter", "device-class": "energy", "state_class": "total"},]
        ],
        "test_responses": [
            b"(00238800!J\r",
        ],
    },
    "QLY": {
        "name": "QLY",
        "description": "Yearly Output Load Energy Inquiry",
        "response_type": ResultType.INDEXED,
        "response": [
            [0, "Output Load Energy for Year", ResponseType.INT, "Wh", {"icon": "mdi:counter", "device-class": "energy", "state_class": "total"},],
            [1, "Year", ResponseType.INFO+":cn[3:]", ""],
        ],
        "test_responses": [
            b"(00238800!J\r",
        ],
        "regex": "QLY(\\d\\d\\d\\d)$",
    },
    "QLM": {
        "name": "QLM",
        "description": "Monthly Output Load Energy Inquiry",
        "response_type": ResultType.INDEXED,
        "response": [
            [0, "Output Load Energy for Month", ResponseType.INT, "Wh", {"icon": "mdi:counter", "device-class": "energy", "state_class": "total"},],
            [1, "Year", ResponseType.INFO+":cn[3:7]", ""],
            [2, "Month", ResponseType.INFO+":calendar.month_name[int(cn[7:])]", ""],
        ],
        "test_responses": [
            b"(00238800!J\r",
        ],
        "regex": "QLM(\\d\\d\\d\\d\\d\\d)$",
    },
    "QLD": {
        "name": "QLD",
        "description": "Daily Output Load Energy Inquiry",
        "response_type": ResultType.INDEXED,
        "response": [
            [0, "Output Load Energy for Day", ResponseType.INT, "Wh", {"icon": "mdi:counter", "device-class": "energy", "state_class": "total"},],
            [1, "Year", ResponseType.INFO+":cn[3:7]", ""],
            [2, "Month", ResponseType.INFO+":calendar.month_name[int(cn[7:9])]", ""],
            [3, "Day", ResponseType.INFO+":cn[9:]", ""],
        ],
        "test_responses": [
            b"(00238800!J\r",
        ],
        "regex": "QLD(\\d\\d\\d\\d\\d\\d\\d\\d)$",
    },
    "QLED": {
        "name": "QLED",
        "description": "LED Status Parameters Inquiry",
        "response_type": ResultType.INDEXED,
        "response": [
            [0, "LED Enabled", ResponseType.OPTION, ["Disabled", "Enabled"]],
            [1, "LED Speed", ResponseType.OPTION, ["Low", "Medium", "Fast"]],
            [2, "LED Effect", ResponseType.OPTION, ["Breathing", "Unknown", "Solid", "Right Scrolling"],],
            [3, "LED Brightness", ResponseType.INT, ""],
            [4, "LED Number of Colors", ResponseType.INT, ""],
            [5, "RGB", ResponseType.BYTES, ""],
        ],
        "test_responses": [
            b"(1 1 2 5 3 148000211255255255000255255\xdaj\r",
        ],
    },
}

SETTER_COMMANDS = {
    "PLEDE": {
        "name": "PLEDE",
        "description": "Enable-Disable LED function",
        "help": " -- examples: PLEDE0 (disable LED), PLEDE1 (enable LED)",
        "regex": "PLEDE([01])$",
    },
    "PLEDS": {
        "name": "PLEDS",
        "description": "Set LED speed",
        "help": " -- examples: PLEDS0 (set LED speed low), PLEDS1 (set LED speed medium), PLEDS2 (set LED speed high)",
        "regex": "PLEDS([012])$",
    },
    "PLEDM": {
        "name": "PLEDM",
        "description": "Set LED effect",
        "help": " -- examples: PLEDM0 (set LED effect breathing), PLEDM2 (set LED effect solid), PLEDM3 (set LED right scrolling)",
        "regex": "PLEDM([0123])$",
    },
    "PLEDB": {
        "name": "PLEDB",
        "description": "Set LED brightness",
        "help": " -- examples: PLEDB1 (set LED brightness low), PLEDB5 (set LED brightness normal), PLEDB9 (set LED brightness high)",
        "regex": "PLEDB([123456789])$",
    },
    "PLEDT": {
        "name": "PLEDT",
        "description": "Set LED total number of colors",
        "help": " -- examples: PLEDT2 (set 2 LED colors), PLEDT3 (set 3 LED colors)",
        "regex": "PLEDT([123])$",
    },
    "PLEDC": {
        "name": "PLEDC",
        "description": "Set LED color",
        "help": " -- examples: PLEDCnRRRGGGBBB (n: 1 line mode, 2 AVR mode, 3 battery mode)",
        "regex": "PLEDC(\\d\\d\\d\\d\\d\\d\\d\\d\\d\\d)$",
    },
}

COMMANDS_TO_REMOVE = ["QVFW2"]


class PI30MAX(PI30):
    """ PI30 protocol handler for LV6048MAX and similar inverters """
    def __str__(self):
        return "PI30 protocol handler for LV6048MAX and similar inverters"

    def __init__(self) -> None:
        super().__init__()
        self.protocol_id = b"PI30MAX"
        # Add pi30max specific commands to pi30 commands
        self.add_command_definitions(NEW_QUERY_COMMANDS)
        # Add pi30max specific setter commands
        self.add_command_definitions(SETTER_COMMANDS, result_type=ResultType.ACK)
        # remove and unwanted pi30 commands
        self.remove_command_definitions(COMMANDS_TO_REMOVE)
        # check for valid load of definitions
        self.check_definitions_count(expected=52)

        self.STATUS_COMMANDS = ["QPIGS", "QPIGS2"]
        self.SETTINGS_COMMANDS = ["QPIRI", "QFLAG"]
        self.DEFAULT_COMMAND = "QPI"
        
